from time import sleep
tabela = ('Bragantino','Bahia','Ceará','Fortaleza','Athletico-PR','Flamengo','Atletico-GO','Sport Recife','Juventude','Cuiabá','Internacional','São Paulo','Fluminense','Grêmio','Atlético-MG','America-MG','Palmeiras','Corinthians','Chapecoense','Santos')
print(f'TABELA DE TIMES {tabela}')
sleep(2)
print('-'*100)
print(f'Os 5 Primeiros Colocados São {tabela[:5]}')
print('-'*100)
sleep(2)
print('-'*100)
print(f'Os 4 Ultimos Colocados São {tabela[-4:20]}')
print('-'*100)
sleep(2)
print('-'*120)
print(f'Os Times em Ordem Alfabetica: {sorted(tabela)}')
print('-'*120)
sleep(2)
print('-'*35)
print(f'O Chapecoense esta na {tabela.index("Chapecoense")+1}ª Posição')
print('-'*35)