precos = ('Lápis', 1.75 , 'Borracha', 2.00 , 'Caderno', 15.90 , 'Estojo', 25.00 , 'Transferidor', 4.20 , 'Compasso', 9.99 , 'Mochila', 120.32 , 'Canetas', 22.30 , 'Livro', 34.90 )
print('-'*40)
print('LISTAGEM DE PREÇOS')
print('-'*40)
print(f'{precos[0]}......................R${precos[1]}')
print(f'{precos[2]}......................R${precos[3]}')
print(f'{precos[4]}......................R${precos[5]}')
print(f'{precos[6]}......................R${precos[7]}')
print(f'{precos[8]}......................R${precos[9]}')
print(f'{precos[10]}.....................R${precos[11]}')
print(f'{precos[12]}.....................R${precos[13]}')
print(f'{precos[14]}.....................R${precos[15]}')
print(f'{precos[16]}.....................R${precos[17]}')
print('-'*40)
